name: TSA Timestamp
description: Generates a Time Stamp Authority signed timestamp to verify when changes occurred.
branding:
  icon: archive
  color: green
on: [push]
run-name: Generating TSA timestamp
jobs:
  Create-Timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install FreeTSA certificates
        run: wget https://freetsa.org/files/tsa.crt; wget https://freetsa.org/files/cacert.pem
      - name: Install zip
        run: sudo apt install zip
      - name: Zip files
        run: zip -r archive.zip $GITHUB_SHA
      - name: Generate timestamp request file
        run: openssl ts -query -data archive.zip -no_nonce -sha512 -cert -out $GITHUB_SHA.tsq
      - name: Download timestamp response file
        run: "curl -H 'Content-Type: application/timestamp-query' --data-binary '@$GITHUB_SHA.tsr"
      - name: Verify timestamp
        run: openssl ts -verify -in $GITHUB_SHA.tsq -CAfile cacert.pem -untrusted tsa.crt
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: timestamp-$GITHUB_SHA
          path: |
            $GITHUB_SHA.tsq
            $GITHUB_SHA.tsr
